network:
  enable: false
  mode: block
  target: host
  cidr:
    allow:
      - 0.0.0.0/0
  domain:
    deny:
      #- example.com
      - baidu.com
  command:
    allow:
      #- systemd-resolved
      #- curl
      #- cu-observer
files:
  enable: false
  mode: block
  target: host
  #allow:
    #- '/'
  deny:
    - '/etc/profile'
    #- '/etc/passwd'
mount:
  enable: false
process:
  enable: true
  mode: monitor
  target: host

log:
  level: debug
  format: json

