network:
  enable: false
  mode: block
  target: host
  cidr:
    allow:
      - 0.0.0.0/0
  domain:
    deny:
      #- example.com
      #- baidu.com
  command:
    allow:
      #- systemd-resolved
      #- curl
      #- safeguard
files:
  enable: true
  mode: block
  target: host
  deny:
    - '/etc/test'
    - '/home/vagrant/test'
mount:
  enable: true
  mode: block
  target: host
  deny:
    - '/dev/vdxn'
process:
  enable: false
  mode: monitor
  target: host
log:
  level: info
  format: json
