network:
  enable: true
  mode: block
  target: host
  cidr:
    allow:
      - 0.0.0.0/0
  domain:
    deny:
      - baidu.com
  command:
    allow:
      #- systemd-resolved
      #- curl
      #- safeguard

files:
  enable: true
  mode: block
  target: host
  deny:
    - '|/home/1|/home/2|/test' # use vertical bar as separation

mount:
  enable: true
  mode: block
  target: host
  deny:
    - '/dev/vdx1|/home/test|/dev/sdx1'

process:
  enable: true
  mode: monitor
  target: host

log:
  level: info
  format: json

